channel_priority: strict
channels:
  - conda-forge
dependencies:
  - r-base=3.6
  - r-tidyverse
  - r-caret
  - r-catools
  - r-cvtools
  - r-data.table
  - r-geosphere
  - r-hdf5r
  - r-leaflet
  - r-matrix
  - r-rcpproll
  - r-rgdal
  - r-unbalanced
  - r-xlsx
  - r-xml
